name: CI/CD

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: rock-academy/rock-front

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER || github.actor }}
          password: ${{ secrets.GHCR_PAT || secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            NEXT_PUBLIC_BACKEND_BASE_URL=http://127.0.0.1:80
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Prepare deploy dir
        run: |
          mkdir -p ~/rock-front/deploy
          cp docker-compose.front.prod.yaml ~/rock-front/
          if [ -f deploy/nginx.front.conf ]; then cp deploy/nginx.front.conf ~/rock-front/deploy/nginx.front.conf; fi

      - name: Log in to GHCR
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
          GHCR_USER: ${{ secrets.GHCR_USER }}
        run: |
          echo "🔍 Checking secrets availability..."
          if [ -z "$GHCR_PAT" ]; then
            echo "❌ GHCR_PAT is empty or not set"
          else
            echo "✅ GHCR_PAT is set"
          fi

          if [ -z "$GHCR_USER" ]; then
            echo "❌ GHCR_USER is empty or not set"
          else
            echo "✅ GHCR_USER is set to: $GHCR_USER"
          fi

          echo ""
          echo "🔐 Attempting login..."
          if [ -n "$GHCR_PAT" ] && [ -n "$GHCR_USER" ]; then
            echo "$GHCR_PAT" | docker login ghcr.io -u "$GHCR_USER" --password-stdin
            echo "✅ Logged in to GHCR with PAT"
          else
            echo "⚠️  Using GITHUB_TOKEN as fallback..."
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            echo "✅ Logged in with GITHUB_TOKEN"
          fi

          echo ""
          echo "🧪 Testing pull access..."
          docker pull ghcr.io/rock-academy/rock-front:latest || echo "❌ Pull test failed"

      - name: Deploy
        env:
          FRONT_IMAGE: ghcr.io/rock-academy/rock-front:latest
        run: |
          cd ~/rock-front
          export NEXT_PUBLIC_BACKEND_BASE_URL=http://localhost:80
          docker compose -f docker-compose.front.prod.yaml pull
          docker compose -f docker-compose.front.prod.yaml up -d
          docker system prune -f
